export const light = {
    name: "light",
    colors: {
        colorPrimary: "#8F4C35",
        colorOnPrimary: "#FFFFFF",
        colorPrimaryContainer: "#FFDBD0",
        colorOnPrimaryContainer: "#390B00",
        colorSecondary: "#77574D",
        colorOnSecondary: "#FFFFFF",
        colorSecondaryContainer: "#FFDBD0",
        colorOnSecondaryContainer: "#2C160E",
        colorTertiary: "#6A5E2F",
        colorOnTertiary: "#FFFFFF",
        colorTertiaryContainer: "#F4E2A7",
        colorOnTertiaryContainer: "#221B00",
        colorError: "#BA1A1A",
        colorOnError: "#FFFFFF",
        colorErrorContainer: "#FFDAD6",
        colorOnErrorContainer: "#410002",
        colorBackground: "#FFF8F6",
        colorOnBackground: "#231917",
        colorSurface: "#FFF8F6",
        colorOnSurface: "#231917",
        colorSurfaceVariant: "#F5DED7",
        colorOnSurfaceVariant: "#53433F",
        colorOutline: "#85736E",
        colorOutlineVariant: "#D8C2BB",
        colorScrim: "#000000",
        colorInverseSurface: "#392E2B",
        colorInverseOnSurface: "#FFEDE8",
        colorInversePrimary: "#FFB59D",
        colorSurfaceDim: "#E8D6D1",
        colorSurfaceBright: "#FFF8F6",
        colorSurfaceContainerLowest: "#FFFFFF",
        colorSurfaceContainerLow: "#FFF1ED",
        colorSurfaceContainer: "#FCEAE5",
        colorSurfaceContainerHigh: "#F7E4DF",
        colorSurfaceContainerHighest: "#F1DFDA",
        colorWhite: "#FFFFFF",
        colorBlack: "#000000",
    }
};


export const dark = {
    name: "dark",
    colors: {
        colorPrimary: "#FFB59D",
        colorOnPrimary: "#55200C",
        colorPrimaryContainer: "#723520",
        colorOnPrimaryContainer: "#FFDBD0",
        colorSecondary: "#E7BDB1",
        colorOnSecondary: "#442A21",
        colorSecondaryContainer: "#5D4036",
        colorOnSecondaryContainer: "#FFDBD0",
        colorTertiary: "#D7C68D",
        colorOnTertiary: "#3A3005",
        colorTertiaryContainer: "#51461A",
        colorOnTertiaryContainer: "#F4E2A7",
        colorError: "#FFB4AB",
        colorOnError: "#690005",
        colorErrorContainer: "#93000A",
        colorOnErrorContainer: "#FFDAD6",
        colorBackground: "#1A110F",
        colorOnBackground: "#F1DFDA",
        colorSurface: "#1A110F",
        colorOnSurface: "#F1DFDA",
        colorSurfaceVariant: "#53433F",
        colorOnSurfaceVariant: "#D8C2BB",
        colorOutline: "#A08D87",
        colorOutlineVariant: "#53433F",
        colorScrim: "#000000",
        colorInverseSurface: "#F1DFDA",
        colorInverseOnSurface: "#392E2B",
        colorInversePrimary: "#8F4C35",
        colorSurfaceDim: "#1A110F",
        colorSurfaceBright: "#423733",
        colorSurfaceContainerLowest: "#140C0A",
        colorSurfaceContainerLow: "#231917",
        colorSurfaceContainer: "#271D1B",
        colorSurfaceContainerHigh: "#322825",
        colorSurfaceContainerHighest: "#3D322F",
        colorBlack: "#FFFFFF",
        colorWhite: "#000000",
    }
};
